### ISSUE TITLE
Error in many panels with Grafana v8.3.4

### ISSUE THREAD

**Issue by Gnomuz** [rfmoz/grafana-dashboards#97]
Hello,
Since upgrading to Grafana v8.3.4, a number of panels are throwing the following error :
bad_data: 1:187: parse error: bad duration syntax: "1m1"
A typical example is the very first panel "CPU Busy" which now shows N/A
Any help will be appreciated

**Comment by Wolfensteijn** [comment]
I removed all the $interval variables in the json, now it is all working again.

**Comment by 2-5** [comment]
I have the same problem:

![1](https://user-images.githubusercontent.com/3753822/150789844-b4d646c6-981c-4341-98cd-583ae791e58f.png)

![2](https://user-images.githubusercontent.com/3753822/150789890-5efaec49-4f83-42c1-afdd-453e5af13993.png)

**Comment by sarus3749** [comment]
![image](https://user-images.githubusercontent.com/34749540/151076201-7080edc5-1bd7-4754-8daa-502a2bb1bf4c.png)
Hello.
Nearly same issue here. I guess this is quite the same reason.
Good luck

**Comment by mentex23** [comment]
i facing the same problem

**Comment by fooness** [comment]
@rfrail3 Will this issue be addressed in terms of an update with fix(es)?

Thank you for all of your efforts. 👍

**Comment by sazarkin** [comment]
Fixed by upgrading prometheus
https://github.com/grafana/grafana/issues/44251

**Comment by mentex23** [comment]
No it will not fix the issue..
I am running Version 2.34.0 with docker

**Comment by LosTigeros** [comment]
I had the same issue. I was using Ubuntu's repo but I noticed those have old versions of `prometheus` and `prometheus-node-exporter`.
I have manually updated them to latest released versions and I don't get that error anymore.

**Comment by northys** [comment]
I also can't confirm this issue. Using latest grafana, prometheus and node-exporter and there are no issues on my dashboard. 

Thera re only some blank graphs (with advanced metrics I don't need) but that's definitely because I haven't enabled some collectors.

**Comment by mentex23** [comment]
@LosTigeros @northys which node_exporter Version do you use? I have still the same issue using Prometheus 2.35 and node_exporter 1.3.1, Grafana 8.4.7

**Comment by northys** [comment]
> which node_exporter Version do you use? I have still the same issue using Prometheus 2.35 (also Docker?) and node_exporter 1.3.1, Grafana 8.4.7

docker:
```
Starting Grafana                         logger=settings version=8.4.2 commit=dea7d4996a branch=HEAD compiled=2022-02-24T11:19:31+0000

/prometheus $ prometheus --version
prometheus, version 2.34.0 (branch: HEAD, revision: 881111fec4332c33094a6fb2680c71fffc427275)
  build user:       root@121ad7ea5487
  build date:       20220315-15:18:00
  go version:       go1.17.8
  platform:         linux/amd64
```

installed using ansible role https://github.com/cloudalchemy/ansible-node-exporter
```
root@nuc ~/docker-prometheus # node_exporter --version
node_exporter, version 1.3.1 (branch: HEAD, revision: a2321e7b940ddcff26873612bccdf7cd4c42b6b6)
  build user:       root@243aafa5525c
  build date:       20211205-11:09:49
  go version:       go1.17.3
  platform:         linux/amd64
```

**Comment by LosTigeros** [comment]
> which node_exporter Version do you use?

Grafana: 8.4.6
Node exporter: 1.3.1
Prometheus: 2.34

**Comment by mentex23** [comment]
I guess I have double checked everything.. it is not working in my case on a rPi 4

**Comment by northys** [comment]
this is all i can provide to you...

docker-compose.yml

```
version: '3.8'

services:
  grafana:
    image: grafana/grafana
    ports:
      - "127.0.0.1:3000:3000/tcp"
    environment:
      GF_RENDERING_SERVER_URL: http://grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_INSTALL_PLUGINS: grafana-image-renderer,grafana-piechart-panel
    restart: unless-stopped
    links:
      - prometheus
      - prometheus-unmonitored
    volumes:
      - "grafana:/var/lib/grafana"

  grafana-renderer:
    image: grafana/grafana-image-renderer:latest

  prometheus:
    image: prometheus
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    restart: unless-stopped
    command:
      # default
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      # custom
      - --storage.tsdb.retention.time=365d
      - --web.enable-admin-api # insecure
    ports:
      - "127.0.0.1:9090:9090/tcp"
    links:
      - alertmanager
    volumes:
      - prometheus-data:/prometheus

  alertmanager:
    image: alertmanager
    build:
      context: .
      dockerfile: Dockerfile.alertmanager
    restart: unless-stopped
    ports:
      - "127.0.0.1:9093:9093/tcp"
    links:
      - alertmanager-bot

volumes:
  prometheus-data:
    external: true
  grafana:
    external: true
```

prometheus.yml
```
scrape_configs:
  # SELFMONITORING
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # EXPORTERS
  - job_name: 'home'
    static_configs:
      - targets:
          - "172.17.0.1:9100" # node_exporter
        labels:
          instance: homelab-server
```
